/// Encounter Note Model for Nurse Encounter Notes
/// Follows the backend API schema

class EncounterNote {
  final String? id;
  final String? encounterNoteNumber;
  final String patientId;
  final String? patientMrn;
  final String? visitId;
  final String? createdByNurseId;
  final String? createdByNurseName;
  final String encounterType;
  final DateTime encounterDatetime;
  final ChiefComplaint? chiefComplaint;
  final PainAssessment? painAssessment;
  final AllergiesData? allergies;
  final List<SymptomData> symptoms;
  final PatientCondition? patientCondition;
  final List<String> appearances;
  final ObservationsData? observations;
  final String? notesForDoctor;
  final String? handoffSummary;
  final bool handoffAutoGenerated;
  final List<CustomSectionData> customSections;
  final String status;
  final bool isLocked;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final DateTime? submittedAt;
  final String? nurseSignature;
  final DateTime? nurseSignedAt;
  final String? reviewedByDoctorId;
  final String? reviewedByDoctorName;
  final DateTime? reviewedAt;
  final String? doctorComments;
  final String? doctorSignature;
  final DateTime? doctorSignedAt;
  final List<Addendum> addendums;

  EncounterNote({
    this.id,
    this.encounterNoteNumber,
    required this.patientId,
    this.patientMrn,
    this.visitId,
    this.createdByNurseId,
    this.createdByNurseName,
    required this.encounterType,
    required this.encounterDatetime,
    this.chiefComplaint,
    this.painAssessment,
    this.allergies,
    this.symptoms = const [],
    this.patientCondition,
    this.appearances = const [],
    this.observations,
    this.notesForDoctor,
    this.handoffSummary,
    this.handoffAutoGenerated = true,
    this.customSections = const [],
    this.status = 'draft',
    this.isLocked = false,
    this.createdAt,
    this.updatedAt,
    this.submittedAt,
    this.nurseSignature,
    this.nurseSignedAt,
    this.reviewedByDoctorId,
    this.reviewedByDoctorName,
    this.reviewedAt,
    this.doctorComments,
    this.doctorSignature,
    this.doctorSignedAt,
    this.addendums = const [],
  });

  /// Convert to JSON for API requests
  Map<String, dynamic> toJson() {
    return {
      if (id != null) 'id': id,
      'patient_id': patientId,
      if (patientMrn != null) 'patient_mrn': patientMrn,
      if (visitId != null) 'visit_id': visitId,
      'encounter_type': encounterType,
      'encounter_datetime': encounterDatetime.toIso8601String(),
      if (chiefComplaint != null) 'chief_complaint': chiefComplaint!.toJson(),
      if (painAssessment != null) 'pain_assessment': painAssessment!.toJson(),
      if (allergies != null) 'allergies': allergies!.toJson(),
      if (symptoms.isNotEmpty)
        'symptoms': symptoms.map((s) => s.toJson()).toList(),
      if (patientCondition != null)
        'patient_condition': patientCondition!.toJson(),
      if (appearances.isNotEmpty) 'appearances': appearances,
      if (observations != null) 'observations': observations!.toJson(),
      if (notesForDoctor != null && notesForDoctor!.isNotEmpty)
        'notes_for_doctor': notesForDoctor,
      if (handoffSummary != null && handoffSummary!.isNotEmpty)
        'handoff_summary': handoffSummary,
      'handoff_auto_generated': handoffAutoGenerated,
      if (customSections.isNotEmpty)
        'custom_sections': customSections.map((s) => s.toJson()).toList(),
      'status': status,
    };
  }

  /// Create from JSON response
  factory EncounterNote.fromJson(Map<String, dynamic> json) {
    return EncounterNote(
      id: json['id'] ?? json['_id'],
      encounterNoteNumber: json['encounter_note_number'],
      patientId: json['patient_id'] ?? json['patient']?['id'] ?? '',
      patientMrn: json['patient_mrn'] ?? json['patient']?['mrn'],
      visitId: json['visit_id'],
      createdByNurseId: json['created_by_nurse_id'] ?? json['created_by']?['id'],
      createdByNurseName: json['created_by_nurse_name'] ?? json['created_by']?['name'],
      encounterType: json['encounter_type'] ?? 'Routine',
      encounterDatetime: json['encounter_datetime'] != null
          ? DateTime.parse(json['encounter_datetime'])
          : DateTime.now(),
      chiefComplaint: json['chief_complaint'] != null
          ? ChiefComplaint.fromJson(json['chief_complaint'])
          : null,
      painAssessment: json['pain_assessment'] != null
          ? PainAssessment.fromJson(json['pain_assessment'])
          : null,
      allergies: json['allergies'] != null
          ? AllergiesData.fromJson(json['allergies'])
          : null,
      symptoms: json['symptoms'] != null
          ? (json['symptoms'] as List)
              .map((s) => SymptomData.fromJson(s))
              .toList()
          : [],
      patientCondition: json['patient_condition'] != null
          ? PatientCondition.fromJson(json['patient_condition'])
          : null,
      appearances: json['appearances'] != null
          ? List<String>.from(json['appearances'])
          : [],
      observations: json['observations'] != null
          ? ObservationsData.fromJson(json['observations'])
          : null,
      notesForDoctor: json['notes_for_doctor'],
      handoffSummary: json['handoff_summary'],
      handoffAutoGenerated: json['handoff_auto_generated'] ?? true,
      customSections: json['custom_sections'] != null
          ? (json['custom_sections'] as List)
              .map((s) => CustomSectionData.fromJson(s))
              .toList()
          : [],
      status: json['status'] ?? 'draft',
      isLocked: json['is_locked'] ?? false,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'])
          : null,
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'])
          : null,
      submittedAt: json['submitted_at'] != null
          ? DateTime.parse(json['submitted_at'])
          : null,
      nurseSignature: json['nurse_signature'],
      nurseSignedAt: json['nurse_signed_at'] != null
          ? DateTime.parse(json['nurse_signed_at'])
          : null,
      reviewedByDoctorId: json['reviewed_by_doctor_id'] ?? json['reviewed_by']?['id'],
      reviewedByDoctorName: json['reviewed_by_doctor_name'] ?? json['reviewed_by']?['name'],
      reviewedAt: json['reviewed_at'] != null
          ? DateTime.parse(json['reviewed_at'])
          : null,
      doctorComments: json['doctor_comments'],
      doctorSignature: json['doctor_signature'],
      doctorSignedAt: json['doctor_signed_at'] != null
          ? DateTime.parse(json['doctor_signed_at'])
          : null,
      addendums: json['addendums'] != null
          ? (json['addendums'] as List)
              .map((a) => Addendum.fromJson(a))
              .toList()
          : [],
    );
  }

  /// Create a copy with updated fields
  EncounterNote copyWith({
    String? id,
    String? encounterNoteNumber,
    String? patientId,
    String? patientMrn,
    String? visitId,
    String? createdByNurseId,
    String? createdByNurseName,
    String? encounterType,
    DateTime? encounterDatetime,
    ChiefComplaint? chiefComplaint,
    PainAssessment? painAssessment,
    AllergiesData? allergies,
    List<SymptomData>? symptoms,
    PatientCondition? patientCondition,
    List<String>? appearances,
    ObservationsData? observations,
    String? notesForDoctor,
    String? handoffSummary,
    bool? handoffAutoGenerated,
    List<CustomSectionData>? customSections,
    String? status,
    bool? isLocked,
  }) {
    return EncounterNote(
      id: id ?? this.id,
      encounterNoteNumber: encounterNoteNumber ?? this.encounterNoteNumber,
      patientId: patientId ?? this.patientId,
      patientMrn: patientMrn ?? this.patientMrn,
      visitId: visitId ?? this.visitId,
      createdByNurseId: createdByNurseId ?? this.createdByNurseId,
      createdByNurseName: createdByNurseName ?? this.createdByNurseName,
      encounterType: encounterType ?? this.encounterType,
      encounterDatetime: encounterDatetime ?? this.encounterDatetime,
      chiefComplaint: chiefComplaint ?? this.chiefComplaint,
      painAssessment: painAssessment ?? this.painAssessment,
      allergies: allergies ?? this.allergies,
      symptoms: symptoms ?? this.symptoms,
      patientCondition: patientCondition ?? this.patientCondition,
      appearances: appearances ?? this.appearances,
      observations: observations ?? this.observations,
      notesForDoctor: notesForDoctor ?? this.notesForDoctor,
      handoffSummary: handoffSummary ?? this.handoffSummary,
      handoffAutoGenerated: handoffAutoGenerated ?? this.handoffAutoGenerated,
      customSections: customSections ?? this.customSections,
      status: status ?? this.status,
      isLocked: isLocked ?? this.isLocked,
      createdAt: createdAt,
      updatedAt: updatedAt,
      submittedAt: submittedAt,
      nurseSignature: nurseSignature,
      nurseSignedAt: nurseSignedAt,
      reviewedByDoctorId: reviewedByDoctorId,
      reviewedByDoctorName: reviewedByDoctorName,
      reviewedAt: reviewedAt,
      doctorComments: doctorComments,
      doctorSignature: doctorSignature,
      doctorSignedAt: doctorSignedAt,
      addendums: addendums,
    );
  }
}

/// Chief Complaint data
class ChiefComplaint {
  final String text;
  final String? preset;
  final bool isQuoted;

  ChiefComplaint({
    required this.text,
    this.preset,
    this.isQuoted = false,
  });

  Map<String, dynamic> toJson() => {
        'text': text,
        if (preset != null) 'preset': preset,
        'is_quoted': isQuoted,
      };

  factory ChiefComplaint.fromJson(Map<String, dynamic> json) {
    return ChiefComplaint(
      text: json['text'] ?? '',
      preset: json['preset'],
      isQuoted: json['is_quoted'] ?? false,
    );
  }
}

/// Pain Assessment data
class PainAssessment {
  final int score;
  final String? location;
  final String? type;
  final String? duration;
  final String? notes;

  PainAssessment({
    required this.score,
    this.location,
    this.type,
    this.duration,
    this.notes,
  });

  Map<String, dynamic> toJson() => {
        'score': score,
        if (location != null) 'location': location,
        if (type != null) 'type': type,
        if (duration != null) 'duration': duration,
        if (notes != null && notes!.isNotEmpty) 'notes': notes,
      };

  factory PainAssessment.fromJson(Map<String, dynamic> json) {
    return PainAssessment(
      score: json['score'] ?? 0,
      location: json['location'],
      type: json['type'],
      duration: json['duration'],
      notes: json['notes'],
    );
  }
}

/// Allergies data container
class AllergiesData {
  final bool noKnownAllergies;
  final List<AllergyItem> items;

  AllergiesData({
    this.noKnownAllergies = false,
    this.items = const [],
  });

  Map<String, dynamic> toJson() => {
        'no_known_allergies': noKnownAllergies,
        'items': items.map((i) => i.toJson()).toList(),
      };

  factory AllergiesData.fromJson(Map<String, dynamic> json) {
    return AllergiesData(
      noKnownAllergies: json['no_known_allergies'] ?? false,
      items: json['items'] != null
          ? (json['items'] as List).map((i) => AllergyItem.fromJson(i)).toList()
          : [],
    );
  }
}

/// Single allergy item
class AllergyItem {
  final String type; // 'drug', 'food', 'other'
  final String name;
  final String reaction;
  final String? severity;

  AllergyItem({
    required this.type,
    required this.name,
    required this.reaction,
    this.severity,
  });

  Map<String, dynamic> toJson() => {
        'type': type,
        'name': name,
        'reaction': reaction,
        if (severity != null) 'severity': severity,
      };

  factory AllergyItem.fromJson(Map<String, dynamic> json) {
    return AllergyItem(
      type: json['type'] ?? 'other',
      name: json['name'] ?? '',
      reaction: json['reaction'] ?? '',
      severity: json['severity'],
    );
  }
}

/// Symptom data with duration and severity
class SymptomData {
  final String name;
  final String? duration;
  final int? severity;
  final String? snomedCode;
  final String? icd10Code;

  SymptomData({
    required this.name,
    this.duration,
    this.severity,
    this.snomedCode,
    this.icd10Code,
  });

  Map<String, dynamic> toJson() => {
        'name': name,
        if (duration != null) 'duration': duration,
        if (severity != null) 'severity': severity,
        if (snomedCode != null) 'snomed_code': snomedCode,
        if (icd10Code != null) 'icd10_code': icd10Code,
      };

  factory SymptomData.fromJson(Map<String, dynamic> json) {
    return SymptomData(
      name: json['name'] ?? '',
      duration: json['duration'],
      severity: json['severity'],
      snomedCode: json['snomed_code'],
      icd10Code: json['icd10_code'],
    );
  }
}

/// Patient condition data
class PatientCondition {
  final String? overallCondition;
  final String? alertnessLevel;
  final String? distressLevel;

  PatientCondition({
    this.overallCondition,
    this.alertnessLevel,
    this.distressLevel,
  });

  Map<String, dynamic> toJson() => {
        if (overallCondition != null) 'overall_condition': overallCondition,
        if (alertnessLevel != null) 'alertness_level': alertnessLevel,
        if (distressLevel != null) 'distress_level': distressLevel,
      };

  factory PatientCondition.fromJson(Map<String, dynamic> json) {
    return PatientCondition(
      overallCondition: json['overall_condition'],
      alertnessLevel: json['alertness_level'],
      distressLevel: json['distress_level'],
    );
  }
}

/// Observations data
class ObservationsData {
  final List<String> items;
  final String? additionalNotes;

  ObservationsData({
    this.items = const [],
    this.additionalNotes,
  });

  Map<String, dynamic> toJson() => {
        'items': items,
        if (additionalNotes != null && additionalNotes!.isNotEmpty)
          'additional_notes': additionalNotes,
      };

  factory ObservationsData.fromJson(Map<String, dynamic> json) {
    return ObservationsData(
      items: json['items'] != null ? List<String>.from(json['items']) : [],
      additionalNotes: json['additional_notes'],
    );
  }
}

/// Custom section data
class CustomSectionData {
  final String title;
  final String? icon;
  final String? color;
  final List<CustomSectionOption> options;
  final String? notes;

  CustomSectionData({
    required this.title,
    this.icon,
    this.color,
    this.options = const [],
    this.notes,
  });

  Map<String, dynamic> toJson() => {
        'title': title,
        if (icon != null) 'icon': icon,
        if (color != null) 'color': color,
        'options': options.map((o) => o.toJson()).toList(),
        if (notes != null && notes!.isNotEmpty) 'notes': notes,
      };

  factory CustomSectionData.fromJson(Map<String, dynamic> json) {
    return CustomSectionData(
      title: json['title'] ?? '',
      icon: json['icon'],
      color: json['color'],
      options: json['options'] != null
          ? (json['options'] as List)
              .map((o) => CustomSectionOption.fromJson(o))
              .toList()
          : [],
      notes: json['notes'],
    );
  }
}

/// Custom section option
class CustomSectionOption {
  final String value;
  final bool selected;

  CustomSectionOption({
    required this.value,
    this.selected = false,
  });

  Map<String, dynamic> toJson() => {
        'value': value,
        'selected': selected,
      };

  factory CustomSectionOption.fromJson(Map<String, dynamic> json) {
    return CustomSectionOption(
      value: json['value'] ?? '',
      selected: json['selected'] ?? false,
    );
  }
}

/// Addendum for corrections after signing
class Addendum {
  final String? id;
  final String addendumText;
  final String reasonForAddendum;
  final String? createdById;
  final String? createdByName;
  final String? createdByRole;
  final DateTime? createdAt;
  final DateTime? signedAt;

  Addendum({
    this.id,
    required this.addendumText,
    required this.reasonForAddendum,
    this.createdById,
    this.createdByName,
    this.createdByRole,
    this.createdAt,
    this.signedAt,
  });

  Map<String, dynamic> toJson() => {
        'addendum_text': addendumText,
        'reason_for_addendum': reasonForAddendum,
      };

  factory Addendum.fromJson(Map<String, dynamic> json) {
    return Addendum(
      id: json['id'] ?? json['_id'],
      addendumText: json['addendum_text'] ?? '',
      reasonForAddendum: json['reason_for_addendum'] ?? '',
      createdById: json['created_by_id'] ?? json['created_by']?['id'],
      createdByName: json['created_by_name'] ?? json['created_by']?['name'],
      createdByRole: json['created_by_role'] ?? json['created_by']?['role'],
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'])
          : null,
      signedAt: json['signed_at'] != null
          ? DateTime.parse(json['signed_at'])
          : null,
    );
  }
}

/// Audit trail entry
class AuditEntry {
  final String? id;
  final String action;
  final Map<String, dynamic>? actionDetails;
  final Map<String, dynamic>? previousValues;
  final Map<String, dynamic>? newValues;
  final String? performedById;
  final String? performedByName;
  final String? performedByRole;
  final String? ipAddress;
  final DateTime? createdAt;

  AuditEntry({
    this.id,
    required this.action,
    this.actionDetails,
    this.previousValues,
    this.newValues,
    this.performedById,
    this.performedByName,
    this.performedByRole,
    this.ipAddress,
    this.createdAt,
  });

  factory AuditEntry.fromJson(Map<String, dynamic> json) {
    return AuditEntry(
      id: json['id'] ?? json['_id'],
      action: json['action'] ?? '',
      actionDetails: json['action_details'],
      previousValues: json['previous_values'],
      newValues: json['new_values'],
      performedById: json['performed_by_id'] ?? json['performed_by']?['id'],
      performedByName: json['performed_by_name'] ?? json['performed_by']?['name'],
      performedByRole: json['performed_by_role'] ?? json['performed_by']?['role'],
      ipAddress: json['ip_address'],
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'])
          : null,
    );
  }
}

